language: R
sudo: true
cache: packages

r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov()'

apt_packages:
  - libcurl4-openssl-dev

notifications:
  email:
    on_success: change
    on_failure: change
